name: Deploy (mkdocs) to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build site (MkDocs)
        run: mkdocs build --strict

      - name: Zip Documentation
        run: |
          cd site
          zip -r ../mkdocs-site.zip .            
        
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force

      # 
      #  Automation for GitHub Release (Tag Push 시, 자동으로 Release 생성 및 Build 업로드)
      #    
      - name: Create GitHub Release and upload build
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            mkdocs-site.zip
          body: |
            🚀 VS Code Documentation Release
            ------------------------------------------
            * **Version**: ${{ github.ref_name }}            
            * **Release Date**: ${{ github.event.head_commit.timestamp }}      
            
            <br/>

            📄 **Documentation: (Supported Mkdocs)**           
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  